# inherit_from: .rubocop_todo.yml

inherit_gem:
  gitlab-styles:
    - rubocop-metrics.yml
      #- rubocop-rspec.yml

require:
  - rubocop-rspec
  - rubocop-performance
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.6
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  CacheRootDirectory: tmp
